import React from 'react'
import Head from 'next/head'
import NavBar from './navbar'
import { Text, Flex } from '@chakra-ui/react'

export default function Layout({ title, children }: { title: string, children: React.ReactNode }) {
    return (
        <>
            <Head>
                <title>{title? title + ' - Dsshop' : 'Dsshop'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Flex flexDirection='column' justify='space-between' minHeight='100vh'>
                <header>
                    <NavBar />
                </header>
                {/* <Container maxW='container.xl' as='main' m='auto' mt='4' px='4'>
                    {children}
                </Container> */}
                <main>
                    {children}
                </main>
                <Flex as='footer' h='10' justify='center' alignItems='center' shadow='inner'>
                    <Text>Copyright © 2022 Dsshop</Text>
                </Flex>
            </Flex>
        </>
    )
}
